"""Trading domain contract — the shared schemas both the framework consumers and
the bot agree on. Strategy code (nodes/agents) lives in ``strategies``; this layer
holds only data shapes and the ``DataProvider`` protocol.

Depends on nothing in ``zetryn`` and never the reverse.
"""

from .schemas import (
    ActivityData,
    AspectAnalysis,
    AuditVerdict,
    ContractData,
    DataProvider,
    Decision,
    FullAnalysis,
    GraduationConfig,
    GraduationContext,
    GraduationEvent,
    GraduationVerdict,
    HolderData,
    KOLAnalystVerdict,
    KOLBuyEvent,
    KOLContext,
    KOLCopyTradeConfig,
    KOLProfile,
    LifecycleConfig,
    LifecycleVerdict,
    MarketData,
    NarrativeScore,
    PartialExit,
    PositionContext,
    PositionState,
    PumpfunData,
    ScannerConfig,
    SniperConfig,
    SocialData,
    TelegramData,
    TokenInput,
    TokenSource,
    TradingContext,
    TwitterData,
    WalletIntel,
)

__all__ = [
    "ActivityData",
    "AspectAnalysis",
    "AuditVerdict",
    "ContractData",
    "DataProvider",
    "Decision",
    "FullAnalysis",
    "GraduationConfig",
    "GraduationContext",
    "GraduationEvent",
    "GraduationVerdict",
    "HolderData",
    "KOLAnalystVerdict",
    "KOLBuyEvent",
    "KOLContext",
    "KOLCopyTradeConfig",
    "KOLProfile",
    "LifecycleConfig",
    "LifecycleVerdict",
    "MarketData",
    "NarrativeScore",
    "PartialExit",
    "PositionContext",
    "PositionState",
    "PumpfunData",
    "ScannerConfig",
    "SniperConfig",
    "SocialData",
    "TelegramData",
    "TokenInput",
    "TokenSource",
    "TradingContext",
    "TwitterData",
    "WalletIntel",
]
